server:
  port: 8080
  servlet:
    context-path: /rs-server
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  error:
    path: /error
    include-stacktrace: never
    whitelabel.enabled: false



spring:
  devtools:
    add-properties: true
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:h2:mem:test
    noticename: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true


rsupport:
  info:
    version: 1.0.0
