server:
  port: 8080
  servlet:
    context-path: /rs-server
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  error:
    path: /error
    include-stacktrace: never
    whitelabel.enabled: false



spring:
  devtools:
    add-properties: true
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:h2:mem:test
    noticename: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true

jwt:
  token:
    header: X-Auth-Token
    secret: rsupport?auth
    # 토큰 만료 시간 (1 day : 86400, 1 week 604800)
    expiration: 86400
    origin: rsupport

rsupport:
  info:
    version: 1.0.0
